name = "cloudflare-deepseek-chat-api"
main = "src/index.js"
compatibility_date = "2024-10-25"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"

# 在 Cloudflare Dashboard 中设置这些环境变量
# DEEPSEEK_API_KEY = "your-deepseek-api-key"
# ALLOWED_ORIGINS = "https://yourdomain.com,https://localhost:3000"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
preview_id = "your-preview-namespace-id"
id = "your-production-namespace-id"

[build]
command = ""

[vars]
# 开发环境变量 (生产环境请在 Cloudflare Dashboard 中设置)
DEEPSEEK_API_BASE = "https://api.deepseek.com"
DEFAULT_MODEL = "deepseek-chat"
MAX_TOKENS = "4000"
